### ISSUE TITLE
How to group all TotalSegmentator classes into 5 groups?

### ISSUE THREAD

**Issue by JiarunLiu** [uni-medical/STU-Net#33]
Hi, Ziyan @Ziyan-Huang 

I noticed that you divided all 104 TotalSegmentator classes into 5 groups (organs, vertebrae, cardiac, muscles, rib) in Table 3 of your paper. But I can't find the corresponding grouping information in the code & paper. How do you divide all classes into 5 groups? I would be very appreciative if you could provide such mapping information.

**Comment by Ziyan-Huang** [comment]
Hi, please refer to https://github.com/wasserth/TotalSegmentator/blob/e36752a6eead41c70695d41a7bfaea3e6d1c21e2/totalsegmentator/map_to_binary.py#L483

**Comment by JiarunLiu** [comment]
Got it. Thank you!
